version: "3"

networks:

        frontend:

        backend:

        monitoring:

volumes:
        acme:

        db:

        certs:

        host:

        site:

        portainer_data:

        gitea-db-v:

        vpn:

        vhost:

        prometheus_data:

        grafana_data:
services:

        nextcloud-db:
                image: mariadb:10.5
                container_name: nextcloud-db
                command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
                restart: always
                volumes:
                        - db:/var/lib/mysql

                env_file:
                        - db.env
                networks:
                        - backend



        nginx-proxy:
                image: jwilder/nginx-proxy:latest
                container_name: nginx-proxy
                labels: 
                        - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"
                restart: always
                ports:
                        - 80:80
                        - 81:81
                        - 443:443
                volumes:
                        - certs:/etc/nginx/certs
                        - vhost:/etc/nginx/vhost.d
                        - site:/usr/share/nginx/html
                        - /var/run/docker.sock:/tmp/docker.sock:ro  
                env_file:
                        - nginx.env
                networks:
                        - frontend
                        - backend
                        - monitoring


        nginx-proxy-letsencrypt:
                image: nginxproxy/acme-companion:latest
                container_name: nginx-proxy-letsencrypt
                restart: always
                depends_on:
                        - nginx-proxy
                volumes:
                        - /var/run/docker.sock:/var/run/docker.sock:ro
                        - acme:/etc/acme.sh
                        - certs:/etc/nginx/certs
                        - vhost:/etc/nginx/vhost.d
                        - site:/usr/share/nginx/html
                env_file:
                        - nginx-le.env
                networks:
                        - backend



        nextcloud:
                image: nextcloud:latest
                container_name: nextcloud
                restart: always
                depends_on:
                        - nextcloud-db
                volumes:
                        - /media/harddrive/nextcloud:/var/www/html
                env_file:
                        - db.env
                        - nextcloud.env
                networks:
                        - backend

        
        ddns-cloudflare-6:
                image: oznu/cloudflare-ddns:latest
                container_name: ddns-cloudflare-6
                restart: always
                network_mode : host
                env_file:
                        - ddns.env
                environment:
                        - "RRTYPE=AAAA"



        ddns-cloudflare-4:
                image: oznu/cloudflare-ddns:latest
                container_name: ddns-cloudflare-4
                restart: always
                network_mode : host
                env_file:
                        - ddns.env
                environment:
                        - "RRTYPE=A"

        
        portainer:
                container_name: portainer
                image: portainer/portainer-ce:latest
                restart: always
                volumes:
                        - /var/run/docker.sock:/var/run/docker.sock
                        - portainer_data:/data
                env_file:
                        - portainer.env
                networks: 
                        - backend

        gitea:
                image: gitea/gitea:latest
                container_name: gitea
                env_file:
                        - gitea.env
                volumes:
                        - /etc/timezone:/etc/timezone:ro
                        - /etc/localtime:/etc/localtime:ro
                        - /media/harddrive/gitea:/data
                depends_on:
                        - gitea-db 
                ports:
                        - "2222:22"          
                networks:
                        - backend

        gitea-db:
                image: mysql:8
                container_name: gitea-db
                restart: always
                env_file:
                        - gitea-db.env
                volumes:
                        - gitea-db-v:/var/lib/mysql
                networks:
                        - backend
        bitwarden:
                image: vaultwarden/server:latest
                container_name: bitwarden
                restart: always
                env_file:
                        - bitwarden.env
                volumes:
                        - /media/harddrive/bitwarden:/data
                networks:
                        - backend
        vpn:
                image: weejewel/wg-easy:latest
                container_name: vpn
                restart: always
                volumes: 
                        - vpn:/etc/wireguard
                cap_add:
                        - NET_ADMIN
                        - SYS_MODULE
                sysctls:
                        - net.ipv4.ip_forward=1
                        - net.ipv4.conf.all.src_valid_mark=1
                env_file:
                        - vpn.env
                ports:
                        - 51820:51820/udp
                networks:
                        - backend
        node-exporter:
                image: prom/node-exporter:latest
                restart: always
                container_name: node-exporter
                volumes:
                        - /proc:/host/proc:ro
                        - /sys:/host/sys:ro
                        - /:/rootfs:ro
                command:
                        - "--path.procfs=/host/proc"
                        - "--path.rootfs=/rootfs"
                        - "--path.sysfs=/host/sys"
                        - "--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)"
                ports:
                        - 9100:9100
                networks:
                        - monitoring
        prometheus:
                image: prom/prometheus:latest
                container_name: prometheus
                restart: always
                volumes:
                        - ./prometheus.yml:/etc/prometheus/prometheus.yml
                        - prometheus_data:/prometheus
                command:
                        - "--config.file=/etc/prometheus/prometheus.yml"
                        - "--storage.tsdb.path=/prometheus"
                        - "--web.console.libraries=/etc/prometheus/console_libraries"
                        - "--web.console.templates=/etc/prometheus/consoles"
                        - "--web.enable-lifecycle"
                        - "--storage.tsdb.retention.time=90d"
                ports:
                        - 9090:9090
                networks:
                        - monitoring
        grafana:
                image: grafana/grafana:latest
                env_file:
                        - grafana.env
                container_name: grafana
                restart: always
                volumes:
                        - ./grafana.ini:/etc/grafana/grafana.ini
                        - grafana_data:/var/lib/grafana
                networks:
                        - monitoring
        collabora:
                image: collabora/code:latest
                env_file:
                        - collabora.env
                container_name: collabora
                restart: always
                expose:
                        - "9980"
                cap_add:
                        - MKNOD
                networks:
                        - backend
